using MathNet.Numerics.LinearAlgebra;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SW2URDF.URDF;
using SW2URDF.URDFExport;
using SW2URDF.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

namespace SW2URDF.UI
{
    /// <summary>
    /// Resolves the SolidWorks context in which a temporary body must be displayed.
    /// Geometry generated by the previews starts in the Link frame. In an assembly,
    /// Display3 accepts a top-level part Component2, or a resolved PartDoc when
    /// that document has exactly one instance in the active assembly. Geometry
    /// must be expressed in the selected host instance's local frame.
    /// </summary>
    internal sealed class TemporaryBodyDisplayContext : IDisposable
    {
        private readonly bool ownsTransform;
        private readonly bool ownsDisplayTarget;
        private readonly bool ownsHideTarget;

        private TemporaryBodyDisplayContext(
            object displayTarget,
            ModelDoc2 hideTarget,
            MathTransform linkToDisplayTarget,
            bool ownsTransform,
            bool ownsDisplayTarget,
            bool ownsHideTarget)
        {
            DisplayTarget = displayTarget;
            HideTarget = hideTarget;
            LinkToDisplayTarget = linkToDisplayTarget;
            this.ownsTransform = ownsTransform;
            this.ownsDisplayTarget = ownsDisplayTarget;
            this.ownsHideTarget = ownsHideTarget;
        }

        public object DisplayTarget { get; }

        public ModelDoc2 HideTarget { get; }

        public MathTransform LinkToDisplayTarget { get; }

        public static bool TryCreate(
            SldWorks swApp,
            ModelDoc2 model,
            Link link,
            MathTransform linkToDocument,
            out TemporaryBodyDisplayContext context,
            out string error)
        {
            context = null;
            error = null;
            if (swApp == null || model == null || linkToDocument == null)
            {
                error = "The SolidWorks application, model, or Link transform is missing.";
                return false;
            }

            if (model.GetType() != (int)swDocumentTypes_e.swDocASSEMBLY)
            {
                context = new TemporaryBodyDisplayContext(
                    model,
                    model,
                    linkToDocument,
                    false,
                    false,
                    false);
                return true;
            }

            Component2 component = link == null || link.SWComponents == null
                ? null
                : link.SWComponents.FirstOrDefault(candidate => candidate != null);
            if (component == null)
            {
                error = "The Link has no SolidWorks component for the temporary-body display context.";
                return false;
            }

            AssemblyDoc assembly = model as AssemblyDoc;
            Component2 preferredComponent = GetTopLevelComponent(
                component,
                out bool ownsPreferredComponent);
            object displayTarget;
            bool ownsDisplayTarget;
            ModelDoc2 hideTarget;
            bool ownsHideTarget;
            Matrix<double> componentToDocumentMatrix;
            if (TryResolveVisiblePartDisplayComponent(
                assembly,
                preferredComponent,
                ownsPreferredComponent,
                out Component2 displayComponent,
                out bool ownsDisplayComponent,
                out ModelDoc2 displayDocument,
                out bool ownsDisplayDocument,
                out componentToDocumentMatrix))
            {
                displayTarget = displayComponent;
                ownsDisplayTarget = ownsDisplayComponent;
                hideTarget = displayDocument;
                ownsHideTarget = ownsDisplayDocument;
            }
            else if (TryResolveUniqueDeepPartDocument(
                assembly,
                out displayDocument,
                out ownsDisplayDocument,
                out componentToDocumentMatrix))
            {
                displayTarget = displayDocument;
                ownsDisplayTarget = ownsDisplayDocument;
                hideTarget = displayDocument;
                ownsHideTarget = false;
            }
            else
            {
                error = ChineseUiText.Translate(
                    "No safe temporary-body host was found. The assembly needs either a top-level part or a resolved part document used by exactly one component instance.",
                    "未找到安全的临时实体宿主。装配体中需要存在顶层零件，或仅被一个组件实例使用的已解析零件文档。");
                return false;
            }

            Matrix<double> linkToDocumentMatrix = MathOps.GetTransformation(linkToDocument);
            Matrix<double> linkToComponentMatrix = BuildLinkToDisplayTarget(
                linkToDocumentMatrix,
                componentToDocumentMatrix);

            MathUtility mathUtility = null;
            MathTransform linkToComponent = null;
            bool displayTargetTransferred = false;
            bool hideTargetTransferred = false;
            try
            {
                mathUtility = swApp.GetMathUtility() as MathUtility;
                if (mathUtility == null)
                {
                    error = "SolidWorks MathUtility is unavailable.";
                    return false;
                }
                linkToComponent = mathUtility.CreateTransform(
                    ToSolidWorksTransformData(linkToComponentMatrix)) as MathTransform;
                if (linkToComponent == null)
                {
                    error = "SolidWorks could not create the Link-to-component transform.";
                    return false;
                }
                context = new TemporaryBodyDisplayContext(
                    displayTarget,
                    hideTarget,
                    linkToComponent,
                    true,
                    ownsDisplayTarget,
                    ownsHideTarget);
                displayTargetTransferred = true;
                hideTargetTransferred = true;
                linkToComponent = null;
                return true;
            }
            finally
            {
                ReleaseComReference(linkToComponent);
                ReleaseComReference(mathUtility);
                if (ownsDisplayTarget && !displayTargetTransferred)
                {
                    ReleaseComReference(displayTarget);
                }
                if (ownsHideTarget && !hideTargetTransferred)
                {
                    ReleaseComReference(hideTarget);
                }
            }
        }

        internal static Matrix<double> BuildLinkToDisplayTarget(
            Matrix<double> linkToDocument,
            Matrix<double> displayTargetToDocument)
        {
            if (linkToDocument == null || displayTargetToDocument == null ||
                linkToDocument.RowCount != 4 || linkToDocument.ColumnCount != 4 ||
                displayTargetToDocument.RowCount != 4 ||
                displayTargetToDocument.ColumnCount != 4)
            {
                throw new ArgumentException("Both transforms must be 4x4 matrices.");
            }
            return displayTargetToDocument.Inverse() * linkToDocument;
        }

        internal static double[] ToSolidWorksTransformData(Matrix<double> transform)
        {
            if (transform == null || transform.RowCount != 4 || transform.ColumnCount != 4)
            {
                throw new ArgumentException("The transform must be a 4x4 matrix.");
            }
            return new[]
            {
                transform[0, 0], transform[1, 0], transform[2, 0],
                transform[0, 1], transform[1, 1], transform[2, 1],
                transform[0, 2], transform[1, 2], transform[2, 2],
                transform[0, 3], transform[1, 3], transform[2, 3],
                1.0, 0.0, 0.0, 0.0
            };
        }

        public void Dispose()
        {
            if (ownsTransform)
            {
                ReleaseComReference(LinkToDisplayTarget);
            }
            if (ownsDisplayTarget)
            {
                ReleaseComReference(DisplayTarget);
            }
            if (ownsHideTarget)
            {
                ReleaseComReference(HideTarget);
            }
        }

        private static Component2 GetTopLevelComponent(
            Component2 component,
            out bool ownsResult)
        {
            Component2 current = component;
            bool ownsCurrent = false;
            while (true)
            {
                Component2 parent;
                try
                {
                    parent = current.GetParent();
                }
                catch
                {
                    if (ownsCurrent)
                    {
                        ReleaseComReference(current);
                    }
                    throw;
                }
                if (parent == null)
                {
                    ownsResult = ownsCurrent;
                    return current;
                }
                if (ownsCurrent)
                {
                    ReleaseComReference(current);
                }
                current = parent;
                ownsCurrent = true;
            }
        }

        private static bool TryResolveVisiblePartDisplayComponent(
            AssemblyDoc assembly,
            Component2 preferredComponent,
            bool ownsPreferredComponent,
            out Component2 displayComponent,
            out bool ownsDisplayComponent,
            out ModelDoc2 displayDocument,
            out bool ownsDisplayDocument,
            out Matrix<double> componentToDocument)
        {
            displayComponent = null;
            ownsDisplayComponent = false;
            displayDocument = null;
            ownsDisplayDocument = false;
            componentToDocument = null;

            object[] topLevelComponents = assembly == null
                ? null
                : assembly.GetComponents(true) as object[];
            var candidates = new List<DisplayComponentCandidate>();
            if (preferredComponent != null)
            {
                candidates.Add(new DisplayComponentCandidate(
                    preferredComponent,
                    ownsPreferredComponent));
            }
            if (topLevelComponents != null)
            {
                foreach (Component2 candidate in topLevelComponents.OfType<Component2>())
                {
                    if (ReferenceEquals(candidate, preferredComponent))
                    {
                        continue;
                    }
                    if (IsSameComponent(candidate, preferredComponent))
                    {
                        ReleaseComReference(candidate);
                        continue;
                    }
                    candidates.Add(new DisplayComponentCandidate(candidate, true));
                }
            }

            try
            {
                foreach (DisplayComponentCandidate candidateReference in candidates)
                {
                    Component2 candidate = candidateReference.Component;
                    if (!IsVisible(candidate))
                    {
                        continue;
                    }

                    MathTransform transform = null;
                    ModelDoc2 partDocument = null;
                    try
                    {
                        if (!TryGetResolvedPartDocument(candidate, out partDocument))
                        {
                            continue;
                        }
                        transform =
                            ReferenceGeometryResolver.GetComponentToRootTransform(candidate);
                        if (transform == null)
                        {
                            continue;
                        }
                        componentToDocument = MathOps.GetTransformation(transform);
                        displayComponent = candidate;
                        ownsDisplayComponent = candidateReference.OwnsReference;
                        displayDocument = partDocument;
                        ownsDisplayDocument = true;
                        candidateReference.OwnsReference = false;
                        partDocument = null;
                        return true;
                    }
                    catch (COMException)
                    {
                        componentToDocument = null;
                    }
                    finally
                    {
                        ReleaseComReference(partDocument);
                        ReleaseComReference(transform);
                    }
                }
                return false;
            }
            finally
            {
                foreach (DisplayComponentCandidate candidate in candidates)
                {
                    if (candidate.OwnsReference)
                    {
                        ReleaseComReference(candidate.Component);
                    }
                }
            }
        }

        private static bool TryResolveUniqueDeepPartDocument(
            AssemblyDoc assembly,
            out ModelDoc2 displayDocument,
            out bool ownsDisplayDocument,
            out Matrix<double> componentToDocument)
        {
            displayDocument = null;
            ownsDisplayDocument = false;
            componentToDocument = null;
            object[] components = assembly == null
                ? null
                : assembly.GetComponents(false) as object[];
            var candidates = new List<DeepPartCandidate>();
            try
            {
                foreach (Component2 component in (components ?? new object[0])
                    .OfType<Component2>())
                {
                    ModelDoc2 partDocument = null;
                    MathTransform transform = null;
                    try
                    {
                        if (!TryGetResolvedPartDocument(component, out partDocument))
                        {
                            continue;
                        }
                        transform = ReferenceGeometryResolver
                            .GetComponentToRootTransform(component);
                        if (transform == null)
                        {
                            continue;
                        }
                        candidates.Add(new DeepPartCandidate(
                            partDocument,
                            GetComIdentity(partDocument),
                            MathOps.GetTransformation(transform)));
                        partDocument = null;
                    }
                    catch (COMException)
                    {
                        // Suppressed and unresolved deep components are not display hosts.
                    }
                    finally
                    {
                        ReleaseComReference(transform);
                        ReleaseComReference(partDocument);
                        ReleaseComReference(component);
                    }
                }

                long? selectedIdentity = SelectUniqueDocumentIdentity(
                    candidates.Select(candidate => candidate.DocumentIdentity));
                DeepPartCandidate selected = selectedIdentity.HasValue
                    ? candidates.FirstOrDefault(candidate =>
                        candidate.DocumentIdentity == selectedIdentity.Value)
                    : null;
                if (selected == null)
                {
                    return false;
                }

                displayDocument = selected.Document;
                ownsDisplayDocument = true;
                componentToDocument = selected.ComponentToDocument;
                selected.OwnsDocument = false;
                return true;
            }
            finally
            {
                foreach (DeepPartCandidate candidate in candidates)
                {
                    if (candidate.OwnsDocument)
                    {
                        ReleaseComReference(candidate.Document);
                    }
                }
            }
        }

        internal static long? SelectUniqueDocumentIdentity(
            IEnumerable<long> documentIdentities)
        {
            if (documentIdentities == null)
            {
                return null;
            }
            return documentIdentities
                .GroupBy(identity => identity)
                .Where(group => group.Count() == 1)
                .Select(group => (long?)group.Key)
                .FirstOrDefault();
        }

        private static bool TryGetResolvedPartDocument(
            Component2 component,
            out ModelDoc2 partDocument)
        {
            partDocument = null;
            if (component == null)
            {
                return false;
            }
            try
            {
                partDocument = component.GetModelDoc2() as ModelDoc2;
                if (partDocument == null ||
                    !IsPartDocument(partDocument.GetType(), null))
                {
                    ReleaseComReference(partDocument);
                    partDocument = null;
                    return false;
                }
                return true;
            }
            catch (COMException)
            {
                ReleaseComReference(partDocument);
                partDocument = null;
                return false;
            }
        }

        private static long GetComIdentity(object value)
        {
            IntPtr unknown = Marshal.GetIUnknownForObject(value);
            try
            {
                return unknown.ToInt64();
            }
            finally
            {
                Marshal.Release(unknown);
            }
        }

        internal static bool IsPartDocument(int? documentType, string path)
        {
            if (documentType.HasValue)
            {
                return documentType.Value == (int)swDocumentTypes_e.swDocPART;
            }

            return String.Equals(
                Path.GetExtension(path ?? String.Empty),
                ".SLDPRT",
                StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsSameComponent(Component2 left, Component2 right)
        {
            if (left == null || right == null)
            {
                return false;
            }
            try
            {
                return String.Equals(
                    left.Name2,
                    right.Name2,
                    StringComparison.OrdinalIgnoreCase);
            }
            catch (COMException)
            {
                return false;
            }
        }

        private sealed class DisplayComponentCandidate
        {
            public DisplayComponentCandidate(Component2 component, bool ownsReference)
            {
                Component = component;
                OwnsReference = ownsReference;
            }

            public Component2 Component { get; }

            public bool OwnsReference { get; set; }
        }

        private sealed class DeepPartCandidate
        {
            public DeepPartCandidate(
                ModelDoc2 document,
                long documentIdentity,
                Matrix<double> componentToDocument)
            {
                Document = document;
                DocumentIdentity = documentIdentity;
                ComponentToDocument = componentToDocument;
                OwnsDocument = true;
            }

            public ModelDoc2 Document { get; }

            public long DocumentIdentity { get; }

            public Matrix<double> ComponentToDocument { get; }

            public bool OwnsDocument { get; set; }
        }

        private static bool IsVisible(Component2 component)
        {
            if (component == null)
            {
                return false;
            }
            try
            {
                return !component.IsHidden(false);
            }
            catch (COMException)
            {
                return false;
            }
        }

        private static void ReleaseComReference(object value)
        {
            try
            {
                if (value != null && Marshal.IsComObject(value))
                {
                    Marshal.ReleaseComObject(value);
                }
            }
            catch (InvalidComObjectException) { }
            catch (COMException) { }
        }
    }
}
