using MathNet.Numerics.LinearAlgebra;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SW2URDF.URDF;
using SW2URDF.Utilities;
using System;
using System.Linq;
using System.Runtime.InteropServices;

namespace SW2URDF.UI
{
    /// <summary>
    /// Resolves the SolidWorks context in which a temporary body must be displayed.
    /// Geometry generated by the previews starts in the Link frame. In an assembly,
    /// Display3 requires a top-level Component2 and geometry expressed in that
    /// component's local frame; an AssemblyDoc is not a valid display context.
    /// </summary>
    internal sealed class TemporaryBodyDisplayContext : IDisposable
    {
        private readonly bool ownsTransform;

        private TemporaryBodyDisplayContext(
            object displayTarget,
            MathTransform linkToDisplayTarget,
            bool ownsTransform)
        {
            DisplayTarget = displayTarget;
            LinkToDisplayTarget = linkToDisplayTarget;
            this.ownsTransform = ownsTransform;
        }

        public object DisplayTarget { get; }

        public MathTransform LinkToDisplayTarget { get; }

        public static bool TryCreate(
            SldWorks swApp,
            ModelDoc2 model,
            Link link,
            MathTransform linkToDocument,
            out TemporaryBodyDisplayContext context,
            out string error)
        {
            context = null;
            error = null;
            if (swApp == null || model == null || linkToDocument == null)
            {
                error = "The SolidWorks application, model, or Link transform is missing.";
                return false;
            }

            if (model.GetType() != (int)swDocumentTypes_e.swDocASSEMBLY)
            {
                context = new TemporaryBodyDisplayContext(model, linkToDocument, false);
                return true;
            }

            Component2 component = link == null || link.SWComponents == null
                ? null
                : link.SWComponents.FirstOrDefault(candidate => candidate != null);
            if (component == null)
            {
                error = "The Link has no SolidWorks component for the temporary-body display context.";
                return false;
            }

            AssemblyDoc assembly = model as AssemblyDoc;
            Component2 preferredComponent = GetTopLevelComponent(component);
            if (!TryResolveVisibleDisplayComponent(
                assembly,
                preferredComponent,
                out Component2 displayComponent,
                out Matrix<double> componentToDocumentMatrix))
            {
                error = "The assembly has no visible top-level component with a valid transform for the temporary-body display context.";
                return false;
            }

            Matrix<double> linkToDocumentMatrix = MathOps.GetTransformation(linkToDocument);
            Matrix<double> linkToComponentMatrix = BuildLinkToDisplayTarget(
                linkToDocumentMatrix,
                componentToDocumentMatrix);

            MathUtility mathUtility = null;
            MathTransform linkToComponent = null;
            try
            {
                mathUtility = swApp.GetMathUtility() as MathUtility;
                if (mathUtility == null)
                {
                    error = "SolidWorks MathUtility is unavailable.";
                    return false;
                }
                linkToComponent = mathUtility.CreateTransform(
                    ToSolidWorksTransformData(linkToComponentMatrix)) as MathTransform;
                if (linkToComponent == null)
                {
                    error = "SolidWorks could not create the Link-to-component transform.";
                    return false;
                }
                context = new TemporaryBodyDisplayContext(
                    displayComponent,
                    linkToComponent,
                    true);
                linkToComponent = null;
                return true;
            }
            finally
            {
                ReleaseComReference(linkToComponent);
                ReleaseComReference(mathUtility);
            }
        }

        internal static Matrix<double> BuildLinkToDisplayTarget(
            Matrix<double> linkToDocument,
            Matrix<double> displayTargetToDocument)
        {
            if (linkToDocument == null || displayTargetToDocument == null ||
                linkToDocument.RowCount != 4 || linkToDocument.ColumnCount != 4 ||
                displayTargetToDocument.RowCount != 4 ||
                displayTargetToDocument.ColumnCount != 4)
            {
                throw new ArgumentException("Both transforms must be 4x4 matrices.");
            }
            return displayTargetToDocument.Inverse() * linkToDocument;
        }

        internal static double[] ToSolidWorksTransformData(Matrix<double> transform)
        {
            if (transform == null || transform.RowCount != 4 || transform.ColumnCount != 4)
            {
                throw new ArgumentException("The transform must be a 4x4 matrix.");
            }
            return new[]
            {
                transform[0, 0], transform[1, 0], transform[2, 0],
                transform[0, 1], transform[1, 1], transform[2, 1],
                transform[0, 2], transform[1, 2], transform[2, 2],
                transform[0, 3], transform[1, 3], transform[2, 3],
                1.0, 0.0, 0.0, 0.0
            };
        }

        public void Dispose()
        {
            if (ownsTransform)
            {
                ReleaseComReference(LinkToDisplayTarget);
            }
        }

        private static Component2 GetTopLevelComponent(Component2 component)
        {
            Component2 current = component;
            while (true)
            {
                Component2 parent = current.GetParent();
                if (parent == null)
                {
                    return current;
                }
                current = parent;
            }
        }

        private static bool TryResolveVisibleDisplayComponent(
            AssemblyDoc assembly,
            Component2 preferredComponent,
            out Component2 displayComponent,
            out Matrix<double> componentToDocument)
        {
            displayComponent = null;
            componentToDocument = null;

            object[] topLevelComponents = assembly == null
                ? null
                : assembly.GetComponents(true) as object[];
            var candidates = new[] { preferredComponent }.Concat(
                topLevelComponents == null
                    ? Enumerable.Empty<Component2>()
                    : topLevelComponents.OfType<Component2>());
            foreach (Component2 candidate in candidates)
            {
                if (!IsVisible(candidate))
                {
                    continue;
                }

                MathTransform transform = null;
                try
                {
                    transform = candidate.Transform2;
                    if (transform == null)
                    {
                        continue;
                    }
                    componentToDocument = MathOps.GetTransformation(transform);
                    displayComponent = candidate;
                    return true;
                }
                catch (COMException)
                {
                    componentToDocument = null;
                }
                finally
                {
                    ReleaseComReference(transform);
                }
            }
            return false;
        }

        private static bool IsVisible(Component2 component)
        {
            if (component == null)
            {
                return false;
            }
            try
            {
                return !component.IsHidden(false);
            }
            catch (COMException)
            {
                return false;
            }
        }

        private static void ReleaseComReference(object value)
        {
            try
            {
                if (value != null && Marshal.IsComObject(value))
                {
                    Marshal.ReleaseComObject(value);
                }
            }
            catch (InvalidComObjectException) { }
            catch (COMException) { }
        }
    }
}
