using MathNet.Numerics.LinearAlgebra;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SW2URDF.URDF;
using SW2URDF.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;

namespace SW2URDF.UI
{
    /// <summary>
    /// Resolves the SolidWorks context in which a temporary body must be displayed.
    /// Geometry generated by the previews starts in the Link frame. In an assembly,
    /// Display3 requires a top-level Component2 and geometry expressed in that
    /// component's local frame; an AssemblyDoc is not a valid display context.
    /// </summary>
    internal sealed class TemporaryBodyDisplayContext : IDisposable
    {
        private readonly bool ownsTransform;
        private readonly bool ownsDisplayTarget;

        private TemporaryBodyDisplayContext(
            object displayTarget,
            MathTransform linkToDisplayTarget,
            bool ownsTransform,
            bool ownsDisplayTarget)
        {
            DisplayTarget = displayTarget;
            LinkToDisplayTarget = linkToDisplayTarget;
            this.ownsTransform = ownsTransform;
            this.ownsDisplayTarget = ownsDisplayTarget;
        }

        public object DisplayTarget { get; }

        public MathTransform LinkToDisplayTarget { get; }

        public static bool TryCreate(
            SldWorks swApp,
            ModelDoc2 model,
            Link link,
            MathTransform linkToDocument,
            out TemporaryBodyDisplayContext context,
            out string error)
        {
            context = null;
            error = null;
            if (swApp == null || model == null || linkToDocument == null)
            {
                error = "The SolidWorks application, model, or Link transform is missing.";
                return false;
            }

            if (model.GetType() != (int)swDocumentTypes_e.swDocASSEMBLY)
            {
                context = new TemporaryBodyDisplayContext(model, linkToDocument, false, false);
                return true;
            }

            Component2 component = link == null || link.SWComponents == null
                ? null
                : link.SWComponents.FirstOrDefault(candidate => candidate != null);
            if (component == null)
            {
                error = "The Link has no SolidWorks component for the temporary-body display context.";
                return false;
            }

            AssemblyDoc assembly = model as AssemblyDoc;
            Component2 preferredComponent = GetTopLevelComponent(
                component,
                out bool ownsPreferredComponent);
            if (!TryResolveVisibleDisplayComponent(
                assembly,
                preferredComponent,
                ownsPreferredComponent,
                out Component2 displayComponent,
                out bool ownsDisplayComponent,
                out Matrix<double> componentToDocumentMatrix))
            {
                error = "The assembly has no visible top-level component with a valid transform for the temporary-body display context.";
                return false;
            }

            Matrix<double> linkToDocumentMatrix = MathOps.GetTransformation(linkToDocument);
            Matrix<double> linkToComponentMatrix = BuildLinkToDisplayTarget(
                linkToDocumentMatrix,
                componentToDocumentMatrix);

            MathUtility mathUtility = null;
            MathTransform linkToComponent = null;
            bool displayComponentTransferred = false;
            try
            {
                mathUtility = swApp.GetMathUtility() as MathUtility;
                if (mathUtility == null)
                {
                    error = "SolidWorks MathUtility is unavailable.";
                    return false;
                }
                linkToComponent = mathUtility.CreateTransform(
                    ToSolidWorksTransformData(linkToComponentMatrix)) as MathTransform;
                if (linkToComponent == null)
                {
                    error = "SolidWorks could not create the Link-to-component transform.";
                    return false;
                }
                context = new TemporaryBodyDisplayContext(
                    displayComponent,
                    linkToComponent,
                    true,
                    ownsDisplayComponent);
                displayComponentTransferred = true;
                linkToComponent = null;
                return true;
            }
            finally
            {
                ReleaseComReference(linkToComponent);
                ReleaseComReference(mathUtility);
                if (ownsDisplayComponent && !displayComponentTransferred)
                {
                    ReleaseComReference(displayComponent);
                }
            }
        }

        internal static Matrix<double> BuildLinkToDisplayTarget(
            Matrix<double> linkToDocument,
            Matrix<double> displayTargetToDocument)
        {
            if (linkToDocument == null || displayTargetToDocument == null ||
                linkToDocument.RowCount != 4 || linkToDocument.ColumnCount != 4 ||
                displayTargetToDocument.RowCount != 4 ||
                displayTargetToDocument.ColumnCount != 4)
            {
                throw new ArgumentException("Both transforms must be 4x4 matrices.");
            }
            return displayTargetToDocument.Inverse() * linkToDocument;
        }

        internal static double[] ToSolidWorksTransformData(Matrix<double> transform)
        {
            if (transform == null || transform.RowCount != 4 || transform.ColumnCount != 4)
            {
                throw new ArgumentException("The transform must be a 4x4 matrix.");
            }
            return new[]
            {
                transform[0, 0], transform[1, 0], transform[2, 0],
                transform[0, 1], transform[1, 1], transform[2, 1],
                transform[0, 2], transform[1, 2], transform[2, 2],
                transform[0, 3], transform[1, 3], transform[2, 3],
                1.0, 0.0, 0.0, 0.0
            };
        }

        public void Dispose()
        {
            if (ownsTransform)
            {
                ReleaseComReference(LinkToDisplayTarget);
            }
            if (ownsDisplayTarget)
            {
                ReleaseComReference(DisplayTarget);
            }
        }

        private static Component2 GetTopLevelComponent(
            Component2 component,
            out bool ownsResult)
        {
            Component2 current = component;
            bool ownsCurrent = false;
            while (true)
            {
                Component2 parent;
                try
                {
                    parent = current.GetParent();
                }
                catch
                {
                    if (ownsCurrent)
                    {
                        ReleaseComReference(current);
                    }
                    throw;
                }
                if (parent == null)
                {
                    ownsResult = ownsCurrent;
                    return current;
                }
                if (ownsCurrent)
                {
                    ReleaseComReference(current);
                }
                current = parent;
                ownsCurrent = true;
            }
        }

        private static bool TryResolveVisibleDisplayComponent(
            AssemblyDoc assembly,
            Component2 preferredComponent,
            bool ownsPreferredComponent,
            out Component2 displayComponent,
            out bool ownsDisplayComponent,
            out Matrix<double> componentToDocument)
        {
            displayComponent = null;
            ownsDisplayComponent = false;
            componentToDocument = null;

            object[] topLevelComponents = assembly == null
                ? null
                : assembly.GetComponents(true) as object[];
            var candidates = new List<DisplayComponentCandidate>();
            if (preferredComponent != null)
            {
                candidates.Add(new DisplayComponentCandidate(
                    preferredComponent,
                    ownsPreferredComponent));
            }
            if (topLevelComponents != null)
            {
                candidates.AddRange(topLevelComponents
                    .OfType<Component2>()
                    .Select(candidate => new DisplayComponentCandidate(candidate, true)));
            }

            try
            {
                foreach (DisplayComponentCandidate candidateReference in candidates)
                {
                    Component2 candidate = candidateReference.Component;
                    if (!IsVisible(candidate))
                    {
                        continue;
                    }

                    MathTransform transform = null;
                    try
                    {
                        transform = candidate.Transform2;
                        if (transform == null)
                        {
                            continue;
                        }
                        componentToDocument = MathOps.GetTransformation(transform);
                        displayComponent = candidate;
                        ownsDisplayComponent = candidateReference.OwnsReference;
                        candidateReference.OwnsReference = false;
                        return true;
                    }
                    catch (COMException)
                    {
                        componentToDocument = null;
                    }
                    finally
                    {
                        ReleaseComReference(transform);
                    }
                }
                return false;
            }
            finally
            {
                foreach (DisplayComponentCandidate candidate in candidates)
                {
                    if (candidate.OwnsReference)
                    {
                        ReleaseComReference(candidate.Component);
                    }
                }
            }
        }

        private sealed class DisplayComponentCandidate
        {
            public DisplayComponentCandidate(Component2 component, bool ownsReference)
            {
                Component = component;
                OwnsReference = ownsReference;
            }

            public Component2 Component { get; }

            public bool OwnsReference { get; set; }
        }

        private static bool IsVisible(Component2 component)
        {
            if (component == null)
            {
                return false;
            }
            try
            {
                return !component.IsHidden(false);
            }
            catch (COMException)
            {
                return false;
            }
        }

        private static void ReleaseComReference(object value)
        {
            try
            {
                if (value != null && Marshal.IsComObject(value))
                {
                    Marshal.ReleaseComObject(value);
                }
            }
            catch (InvalidComObjectException) { }
            catch (COMException) { }
        }
    }
}
