; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SolidWorks To URDF"
#define MyAppPublisher "OSRBot / kitso666"
#define MyAppURL "https://github.com/osrbot/solidworks_urdf_exporter_pro"

#define MainBinaryName  "SW2URDF.dll"
#define SetupBaseName   "sw2urdfSetup_"
#ifndef BuildConfiguration
  #define BuildConfiguration "Release"
#endif
#ifndef BuildPlatform
  #define BuildPlatform "x64"
#endif
#define BuildOutputPath AddBackslash(SourcePath + "..\SW2URDF\bin\" + BuildPlatform + "\" + BuildConfiguration)
#define DllLocation     BuildOutputPath + MainBinaryName
#define BuildVersion    GetVersionNumbersString(DllLocation)
#define CommitVersion   GetFileProductVersion(DllLocation)
#if CommitVersion == ""
  #define InstallerVersion BuildVersion
  #define DefaultInstallerCommit "unknown"
#else
  #define InstallerVersion CommitVersion
  #define DefaultInstallerCommit CommitVersion
#endif
#ifndef InstallerDate
  #define InstallerDate "unknown_date"
#endif
#ifndef InstallerCommit
  #define InstallerCommit DefaultInstallerCommit
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E43E85A9-071D-430A-91B2-84B7AB923170}
AppName={#MyAppName}
AppVersion={#InstallerVersion}
VersionInfoVersion={#BuildVersion}
VersionInfoCopyright=2019
VersionInfoProductName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=yes
DisableDirPage=no
UsePreviousAppDir=yes
OutputBaseFilename={#SetupBaseName + InstallerDate + "_" + InstallerCommit}
Compression=lzma
DefaultDirName="{autopf}\SolidWorks Corp\SolidWorks\URDFExporter"
SolidCompression=no
PrivilegesRequired=admin
OutputDir=..\..\INSTALL\OUTPUT
SourceDir=..\SW2URDF\bin\
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Default.isl,{#AddBackslash(SourcePath) + "Languages\ChineseSimplified.isl"}"

[CustomMessages]
english.RegisteringControls=Registering SolidWorks URDF exporter...
english.UnregisteringControls=Unregistering SolidWorks URDF exporter...
english.DotNet48Required=Microsoft .NET Framework 4.8 or later is required. Install it, restart Windows if requested, and run this installer again.
chinesesimplified.RegisteringControls=正在注册 SolidWorks URDF 导出插件...
chinesesimplified.UnregisteringControls=正在注销 SolidWorks URDF 导出插件...
chinesesimplified.DotNet48Required=需要 Microsoft .NET Framework 4.8 或更高版本。请先安装，按提示重启 Windows，然后重新运行本安装程序。

[InstallDelete]
; Installed payloads are immutable. Remove the previous version before copying so a renamed
; assembly, schema, image, adapter, runtime or license file cannot survive an in-place upgrade.
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\SW2URDF.png"
Type: files; Name: "{app}\LICENSE"
Type: files; Name: "{app}\THIRD_PARTY_NOTICES.md"
Type: filesandordirs; Name: "{app}\images"
Type: filesandordirs; Name: "{app}\schemas"
Type: filesandordirs; Name: "{app}\THIRD_PARTY_LICENSES"
Type: filesandordirs; Name: "{app}\tools"

[Files]
Source: {#BuildPlatform + "\" + BuildConfiguration + "\*.dll"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\SW2URDF.png"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\images\*.png"}; DestDir: {app}\images; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\LICENSE"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\THIRD_PARTY_NOTICES.md"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\THIRD_PARTY_LICENSES\*"}; DestDir: {app}\THIRD_PARTY_LICENSES; Flags: ignoreversion recursesubdirs createallsubdirs; Check: IsWin64;
; Install only current public schema entrypoints. Isaac/Isaac Lab schemas remain in source for
; historical document parsing, but are internal legacy contracts and are not UI-loaded payloads.
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\README.md"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\robot.schema.v2.json"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\robot.schema.v3.json"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\robot-bundle-manifest.schema.v1.json"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\ros2-control-profile.schema.v1.json"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\schemas\ros2-control-profile.example.json"}; DestDir: {app}\schemas; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\tools\usd_adapter\*"}; DestDir: {app}\tools\usd_adapter; Flags: ignoreversion recursesubdirs createallsubdirs; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\tools\openusd_runtime\*"}; DestDir: {app}\tools\openusd_runtime; Flags: ignoreversion recursesubdirs createallsubdirs; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\tools\openusd_runtime.lock.json"}; DestDir: {app}\tools; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\tools\mujoco_runtime\*"}; DestDir: {app}\tools\mujoco_runtime; Flags: ignoreversion recursesubdirs createallsubdirs; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\tools\mujoco_runtime.lock.json"}; DestDir: {app}\tools; Flags: ignoreversion; Check: IsWin64;
;Source: x86\Debug\*;  DestDir: {app}; Flags: regserver ignoreversion; Check: not IsWin64

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]                                                        
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters: """{app}\SW2URDF.dll"" ""/codebase"""; StatusMsg: "{cm:RegisteringControls}"; Check: IsWin64;


[UninstallRun]

Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters:  """{app}\SW2URDF.dll"" ""/unregister"""; StatusMsg: "{cm:UnregisteringControls}"; Check: IsWin64 and CurrentInstallOwnsComRegistration; RunOnceId: "UnregisterSW2URDF";

[UninstallDelete]
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\SW2URDF.png"
Type: files; Name: "{app}\LICENSE"
Type: files; Name: "{app}\THIRD_PARTY_NOTICES.md"
Type: filesandordirs; Name: "{app}\images"
Type: filesandordirs; Name: "{app}\schemas"
Type: filesandordirs; Name: "{app}\THIRD_PARTY_LICENSES"
Type: filesandordirs; Name: "{app}\tools"

[Code]
const
  Sw2UrdfComRegistrationKey = 'SOFTWARE\Classes\CLSID\{65c9fc17-6a74-45a3-8f84-55185900275d}\InprocServer32';
  DotNet48MinimumRelease = 528040;

function IsDotNet48Installed(): Boolean;
var
  Release: Cardinal;
begin
  Result := False;
  if RegQueryDWordValue(
    HKLM64,
    'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full',
    'Release',
    Release) then
  begin
    if Release >= DotNet48MinimumRelease then
    begin
      Result := True;
      Exit;
    end;
  end;
  if RegQueryDWordValue(
    HKLM32,
    'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full',
    'Release',
    Release) then
    Result := Release >= DotNet48MinimumRelease;
end;

function InitializeSetup(): Boolean;
begin
  Result := IsDotNet48Installed();
  if not Result then
    MsgBox(ExpandConstant('{cm:DotNet48Required}'), mbError, MB_OK);
end;

function NormalizeCodeBasePath(Value: String): String;
begin
  Result := Trim(Value);
  if CompareText(Copy(Result, 1, 8), 'file:///') = 0 then
    Delete(Result, 1, 8);
  StringChangeEx(Result, '/', '\', True);
end;

function CurrentInstallOwnsComRegistration(): Boolean;
var
  RegisteredCodeBase: String;
  RegisteredPath: String;
  ExpectedPath: String;
begin
  Result := False;
  if not RegQueryStringValue(
    HKLM64, Sw2UrdfComRegistrationKey, 'CodeBase', RegisteredCodeBase) then
  begin
    Log('Skipping COM unregistration: the SW2URDF CodeBase is not registered.');
    Exit;
  end;

  RegisteredPath := NormalizeCodeBasePath(RegisteredCodeBase);
  ExpectedPath := NormalizeCodeBasePath(ExpandConstant('{app}\SW2URDF.dll'));
  Result := CompareText(RegisteredPath, ExpectedPath) = 0;
  if not Result then
    Log('Skipping COM unregistration: this installer does not own the active SW2URDF registration. ' +
      'Registered=' + RegisteredPath + '; Expected=' + ExpectedPath);
end;
