; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SolidWorks To URDF"
#define MyAppVersion "2018 v1.6"
#define MyAppPublisher "OSRBot / kitso666"
#define MyAppURL "https://github.com/osrbot/solidworks_urdf_exporter_pro"

#define MainBinaryName  "SW2URDF.dll"
#define SetupBaseName   "sw2urdfSetup_"
#ifndef BuildConfiguration
  #define BuildConfiguration "Release"
#endif
#ifndef BuildPlatform
  #define BuildPlatform "x64"
#endif
#define BuildOutputPath AddBackslash(SourcePath + "..\SW2URDF\bin\" + BuildPlatform + "\" + BuildConfiguration)
#define DllLocation     BuildOutputPath + MainBinaryName
#define BuildVersion    GetVersionNumbersString(DllLocation)
#define CommitVersion   GetFileProductVersion(DllLocation)
#if CommitVersion == ""
  #define InstallerVersion BuildVersion
  #define DefaultInstallerCommit "unknown"
#else
  #define InstallerVersion CommitVersion
  #define DefaultInstallerCommit CommitVersion
#endif
#ifndef InstallerDate
  #define InstallerDate "unknown_date"
#endif
#ifndef InstallerCommit
  #define InstallerCommit DefaultInstallerCommit
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E43E85A9-071D-430A-91B2-84B7AB923170}
AppName={#MyAppName}
AppVersion={#InstallerVersion}
VersionInfoVersion={#BuildVersion}
VersionInfoCopyright=2019
VersionInfoProductName={#MyAppName}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=yes
DisableDirPage=no
UsePreviousAppDir=yes
OutputBaseFilename={#SetupBaseName + InstallerDate + "_" + InstallerCommit}
Compression=lzma
DefaultDirName="{autopf}\SolidWorks Corp\SolidWorks\URDFExporter"
SolidCompression=no
PrivilegesRequired=admin
OutputDir=..\..\INSTALL\OUTPUT
SourceDir=..\SW2URDF\bin\
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Default.isl,{#AddBackslash(SourcePath) + "Languages\ChineseSimplified.isl"}"

[CustomMessages]
english.RegisteringControls=Registering SolidWorks URDF exporter...
english.UnregisteringControls=Unregistering SolidWorks URDF exporter...
chinesesimplified.RegisteringControls=正在注册 SolidWorks URDF 导出插件...
chinesesimplified.UnregisteringControls=正在注销 SolidWorks URDF 导出插件...

[Files]
Source: {#BuildPlatform + "\" + BuildConfiguration + "\*.dll"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\SW2URDF.png"}; DestDir: {app}; Flags: ignoreversion; Check: IsWin64;
Source: {#BuildPlatform + "\" + BuildConfiguration + "\images\*.png"}; DestDir: {app}\images; Flags: ignoreversion; Check: IsWin64;
;Source: x86\Debug\*;  DestDir: {app}; Flags: regserver ignoreversion; Check: not IsWin64

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]                                                        
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters: """{app}\SW2URDF.dll"" ""/codebase"""; StatusMsg: "{cm:RegisteringControls}"; Check: IsWin64;


[Registry]
Root: HKLM64; Subkey: "SOFTWARE\SolidWorks\Addins\{{65c9fc17-6a74-45a3-8f84-55185900275d}";        ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64
Root: HKCU64; Subkey: "Software\SolidWorks\AddInsStartup\{{65c9fc17-6a74-45a3-8f84-55185900275d}"; ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64

[UninstallRun]

Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters:  """{app}\SW2URDF.dll"" ""/unregister"""; StatusMsg: "{cm:UnregisteringControls}"; Check: IsWin64; RunOnceId: "UnregisterSW2URDF";
